### ISSUE TITLE
Regarding the confusion

### ISSUE THREAD

**Issue by Rahuletto** [unixporn-dots/unixporn-dots.github.io#11]
As I said earlier. We need to have a separate property called wm or something rather than having it in the first element of the array from tags. This causes a rather big confusion among the users.

**Comment by armoredvortex** [comment]
Yep, a separate entry for the wm would definitely sort it all out

**Comment by armoredvortex** [comment]
c0cf67d6f70e309dcffc908a944a09a4900b2ade fixes it.
