### ISSUE TITLE
Arranging setups into separate folders

### ISSUE THREAD

**Issue by armoredvortex** [unixporn-dots/unixporn-dots.github.io#25]
The current way of storing setups is pretty ugly.
Would be nice to have all the setups into their own separate folders as mentioned on this reddit thread below.
https://www.reddit.com/r/unixporn/comments/vz447g/comment/ig9aglf/?utm_source=share&utm_medium=web2x&context=3

**Comment by Pesc0** [comment]
Well, the problem comes from hosting the site on github. Which is not that bad afterall, since hosting is complicated and expensive. How about a quick python script that parses the folders and auto generates the js file? i dont really know how github workflows work but if it is possible to run said script before each deploy we are in business id say.

Also while searching i found that github pages have quite a bit of limitations, namely max 1G repo size and 100G monthly traffic. if you start adding themes you will run into those real quick i think.

**Comment by Rahuletto** [comment]
Doesn't making it in separate folders increase file size and decrease performance??

It does make things clean but many prefer to use the method we are already using (many big communities like js.org and so on)

**Comment by Rahuletto** [comment]
We can try hosting the site in netlify or other hosts @ArmoredVortex if we come across any limitations in github pages

**Comment by armoredvortex** [comment]
Hosting is indeed complicated and can be expensive because most free tiers are pretty much real low spec and limited

The bulkiest part of the repo are the images, but if we ever run into the 1gb repo limit, we can just move over all the images to imgur or some other service and reference the url instead of having the image on the repo itself.

Github workflows might be the best option at this point i guess.
And as Rahul mentioned netifly has a good free tier and we can always move there in case of issues with github pages.

**Comment by Rahuletto** [comment]
Images do have metadata. I have an idea of using the data instead of files but I don't know how to literally implement that

And the image data can be viewed even offline (meaning we do not need a hosting for the image)

**Comment by Pesc0** [comment]
> Doesn't making it in separate folders increase file size and decrease performance??

No not really. You're going to add a couple of KB which is nothing compared even to a single image. I don't see how that would impact performance. And even if it did in the slightest you're not doing disk intensive computation, its just a webpage. i dont think its valuable trying to optimize space: if space becomes a problem squeezing kilobytes certainly wont fix it.

**Comment by Rahuletto** [comment]
> > Doesn't making it in separate folders increase file size and decrease performance??
> 
> No not really. 

~~Im talking about the performance in the client (user's) device. Not everyone owns a gaming beast. So adding a little bit of KB hits many devices~~

~~And we are not rendering things in the best optimal way either~~

Ok ArmoredVortex explained me briefly and yea it's possible

**Comment by armoredvortex** [comment]
A github actions node script to automatically compile all the separate file into one before deployment seems like the best way to go.

**Comment by armoredvortex** [comment]
Big thanks to @Pesc0 for #30 
The github workflow is setup and i've verified it works :+1: 
I suppose this can be closed now.
