### ISSUE TITLE
[NEWTHEME] b9k's dotfiles

### ISSUE THREAD

**Issue by beyond9thousand** [unixporn-dots/unixporn-dots.github.io#27]
```js
{
    title: "b9k's dotfiles",
    author: "beyond9thousand",
    link: "https://github.com/beyond9thousand/dotfiles",
    description: "Opinionated BSPWM setup",
    image: "assets/final.png",
    wm: "bspwm",
    tags: ['bspwm', 'nvim', 'rofi', 'ranger', 'dunst', 'blender' 'jgmenu', 'arch', 'polybar', 'alacritty', 'tokyonight']
}
```

**Comment by armoredvortex** [comment]
Hi, can i get a link to the image you wish to use?

**Comment by armoredvortex** [comment]
I found the image at your github repository under `assets/final.png`

Thanks for the submissions and the awesome dots!
Your dots should be up on the site now.

**Comment by beyond9thousand** [comment]
my bad, i initially assumed that following the format would just do the trick. sorry for the extra trouble, and thank you!

**Comment by armoredvortex** [comment]
no worries :)

Sent from Proton Mail mobile

-------- Original Message --------
