### ISSUE TITLE
Categorise items to expand the site

### ISSUE THREAD

**Issue by Rahuletto** [unixporn-dots/unixporn-dots.github.io#29]
# ` Enhancement `

We have high expectations to make this a linux customising centre. This may be the first move towards that.

As the title says, We do wanna categorise things like `dots`, `icons`, `vim configs` and so on.

For this purpose, I moved the image button to an optimal place. Giving room for category icons in the pull request https://github.com/unixporn-dots/unixporn-dots.github.io/pull/28

I'm planning to create a drop-down box to make it easy to navigate through categories

This is a very low priority issue.

**Comment by Rahuletto** [comment]
You may be thinking of renaming the site/repo but I think there is no reason to. Apple doesn't sell apples, they sell tech products. The same thing goes on here. We do prioritise dotfiles

**Comment by Rahuletto** [comment]
This is made into a priority I guess. What do u think @ArmoredVortex

**Comment by armoredvortex** [comment]
Yep, we can start working on this one now finally
