### ISSUE TITLE
Moving buttons to card header & using icons instead of text

### ISSUE THREAD

**Issue by ManorSailor** [unixporn-dots/unixporn-dots.github.io#31]
How about moving buttons from the card to header & making the tag invisible on hover? There are too many things going on when you hover over a card, buttons are quite big & they take up quite space over the image. Besides, replacing the text with icons for repo, reddit etc from font-awesome or locally uploaded SVGs would be better.

I have already been working on this, and might open a PR soon. Though, I am opening this issue just in case there are some other plans for it

**Comment by armoredvortex** [comment]
Yep, there have been talks about how cluttered the cards feel when hovering and i suppose your solution is pretty reasonable.
Thanks for the issue, we'd be waiting for the pr

**Comment by Pesc0** [comment]
That would be perfect! I just reorganized a ton of js, hope that doesn't mess with the work you have already done. `generateCards` is mostly untouched though, so you should be good. In addition to what you have suggested, i would remove the image button completely, making the image clickable to open the preview.

**Comment by ManorSailor** [comment]
> That would be perfect! I just reorganized a ton of js, hope that doesn't mess with the work you have already done. `generateCards` is mostly untouched though, so you should be good. In addition to what you have suggested, i would remove the image button completely, making the image clickable to open the preview.

Welp. I have been refactoring JS as well. No problem, I will discard my changes & fix merge conflicts if any.
Also, nice idea about image pop-up on click on the image

**Comment by Pesc0** [comment]
Perfect, thank you! Feel free to discard any of my changes if needed.
