### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pesc0** [unixporn-dots/unixporn-dots.github.io#46]
what needs work right now?
things i noticed could be improved:
- some of the thumbnails look stretched (on the icons page)
- the menu to select dotfiles/icons/gtk looks a bit weird; the mouse doesn't change shape when hovering
- haven't seen multi image work yet: which themes have more than one image? also: arrows should be hidden when only one image is present.
- add the possibility to close image preview by clicking on the dark background instead of the X on the top right.

Add anything you can think of so we can have a todo-list kind of thing.

**Comment by armoredvortex** [comment]
>     * some of the thumbnails look stretched (on the icons page)
Can be fixed by either manually cropping images or some sort of css magic to automatically zoom into the image to correct for aspect ratio.
Maybe even a github actions script which generates new image files and crops them (no idea how thats gonna work out)

>     * haven't seen multi image work yet: which themes have more than one image? also: arrows should be hidden when only one image is present.
Most stuff in the icons page have multiple images. (some dotfiles also do but its like 2-3 maybe)
>     * add the possibility to close image preview by clicking on the dark background instead of the X on the top right.
Yep, its annoying to move the mouse all the way to the corner

**Comment by Pesc0** [comment]
Oh you're right, icons do have more than one image. i didnt notice because theres no preview at the bottom, you have to click the arrows. so..
- add multi image preview between arrows

**Comment by Rahuletto** [comment]
What's the progress?

**Comment by armoredvortex** [comment]
> What's the progress?

Its stale at this point and I haven't had any free time lately from academics to manage any of the projects sorry

**Comment by Rahuletto** [comment]
Or I'll take care of this issue and try to implement it in my free time

**Comment by Pesc0** [comment]
I have very little free time atm, sorry

**Comment by Pesc0** [comment]
Adding to the list:
- Bug: yaru-colors (gtk) image view looks smaller than other themes. I have a feeling its caused by a lower image resolution, but havent looked into it. Wold be more consistent if everything had the same size. Perhaps add ability to zoom?

**Comment by Rahuletto** [comment]
Most of the things addressed here is now made possible with #49

**Comment by Rahuletto** [comment]
i hope this issue can be closed because everything got added in #49
