### ISSUE TITLE
[No Issue] please read description

### ISSUE THREAD

**Issue by Pesc0** [unixporn-dots/unixporn-dots.github.io#55]
Hey guys @ArmoredVortex @Rahuletto, long time no see. 
I am currently contributing to FreeCAD, and yesterday I stumbled upon something that made me think of you here. 
See, I am familiar with python and c++, but the freecad's start page is html, js and all of that. Heres what it looks like:

![Screenshot from 2023-06-15 12-36-06](https://github.com/unixporn-dots/unixporn-dots.github.io/assets/54720203/81ff1db2-e4d6-435c-aba3-0da9c7498619)
![Screenshot from 2023-06-15 12-36-11](https://github.com/unixporn-dots/unixporn-dots.github.io/assets/54720203/0fbb8a91-d1e3-4bf3-91b4-86165910eb6d)
![Screenshot from 2023-06-15 12-36-42](https://github.com/unixporn-dots/unixporn-dots.github.io/assets/54720203/115ff3c3-9a3a-486f-bc9c-3cbfccb11ec8)

It's a mess, It's very old and could get some restyling. And the code underneath is even more ugly. 
So if you're up for a sidequest you would be very welcome to help here :)

All the relative files are contained in [src/Mod/Start](https://github.com/FreeCAD/FreeCAD/tree/master/src/Mod/Start) if you want to take a look.

Feel free to close this issue anytime, I thought this was the best way to get in touch. cheers!

**Comment by Rahuletto** [comment]
Uhh you created a "No Issue" in a issue tab lol. You could've contacted us in other platforms or email for this. But yea I'll take a glance at it. Thanks

**Comment by Rahuletto** [comment]
i dont know if its actually intended to be like that. because of the color choices they made there 💀

**Comment by Pesc0** [comment]
> Uhh you created a "No Issue" in a issue tab lol

Yeah my bad. I got to know you guys form here, so I came here looking for you. We can move the discussion wherever you want. 

> i dont know if its actually intended to be like that. because of the color choices they made there 

Might be the theme I applied messing with it as well. still it's very old so there's the explanation for the colors.
Thanks for helping!

**Comment by Rahuletto** [comment]
No problem 😊. If u need to contact me, you can with discord. This is my tag `Rahuletto#0243`.

**Comment by Pesc0** [comment]
Sent! closing this issue then

**Comment by armoredvortex** [comment]
Apologies, The project is really intriguing and would've been a great opportunity to learn a lot of stuff and improve but I'm unable to contribute as I'm busy with school.

**Comment by Pesc0** [comment]
Hey thanks for reaching out. No worries, I totally understand as I am quite busy with university exams too ;)
Best of luck!
