### ISSUE TITLE
Dot's with long titles

### ISSUE THREAD

**Issue by A-K-O-R-A** [unixporn-dots/unixporn-dots.github.io#9]
When dots have too long titles the CSS glitches out when you hover over it.

**Without hovering:**
![grafik](https://user-images.githubusercontent.com/65976562/168655725-d2ce5960-1259-45d2-9dee-6ee8f40eb32a.png)

**While hovering:**
![grafik](https://user-images.githubusercontent.com/65976562/168655764-f623f738-fa67-4c9c-982a-f848ec52d958.png)

**Comment by Rahuletto** [comment]
We are working on this issue. Thanks in advance mate ❤️

**Comment by armoredvortex** [comment]
Thanks @Rahuletto for the #12 PR . I suppose this issue is resolved now.
